---
title: "lsss_course - Hafró/MFRI April 2018"
author: "Training course and workshop in the use of LSSS at Hafró/MFRI, April 2018"
output:
  html_document: default
bibliography: lsss_course.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Preamble
___

## The course material

Course materials prepared at Hafró are open source, meaning that presentations, code, etc is made freely available and may be
redistributed and modified (with wich license these pages' framework
is lifted from 'http://github.com/fishvice/tcrenv').

* The source code for the course material is located at:
  https://github.com/sigurdurthorjonsson/lsss_course

* The course product will be rendered in 'Holy week/Dymbilvikan' and revised as we progress during April at:
  http://www.hafro.is/~sigurdur/lsss_course
  

## In preparation

The aim of the course is to train Hafró-personnel in the use of the
acoustic post-processing program LSSS (for Large Scale Survey
System). The program is written and maintained by Marec, a
collaboration between Havforskningen/IMR and Christian Michelsen
Research/CMR in Bergen. The software is licenced and the user
generally has to have a licence dongle on the machine running the
program.
 
**Prior to the course** please try to install:

* LSSS version 2.3.0, for a local install follow Gunnar Örvarsson's instructions:

    - Windows: Windows version of LSSS 2.3.0 is available on a
      package-directory, `m:\inst\lsss` on shore on server hafkaldi, on
      board the vessels on server stórsjór (on Árni) or úthaf (on
      Bjarni)).

    - linux: Linux version can be updated to 2.3.0 (as root) with:

> cd /net/hafkaldi.hafro.is/opt/hafkaldi/local/src/linux

> make lsss-update

    - Mac, go figure, ...

Hafró has 5 dongles which can be borrowed for periods of time not
colliding with high acoustic survey activity (January/February,
September/October). __Marec/IMR in Bergen will open up for dongle-less
use of the program in April.__

### Simrad's EK-programs

Prior to the course recent installation programs for Simrad ER60
(current) and EK80 (future) scientific echosounder programs were made
available on Hafro-net by Björn Sigurðarson, in folder:

  * `v:\bi500\Simrad` on Windows
  * `/net/hafkaldi/export/u3/bi500/Simrad` on linux

Documentation for these programs and other materials can be found by following [this](https://www.simrad.com/www/01/nokbg0237.nsf/AllWeb/D45E29163DDC0921C1257106003C8C78?OpenDocument) link to Simrad's website. The following links lead directly to the reference manuals:

  * For [EK60](https://www.simrad.com/www/01/NOKBG0397.nsf/AllWeb/F2AB311B3F6E6B15C1257106003E0806/$file/164692ad_ek60_reference_manual_english_lores.pdf?OpenElement)
  * For [EK80](https://www.simrad.com/www/01/NOKBG0397.nsf/AllWeb/AFFDFFE472BCFBF7C1257E5100291B04/$file/395234af_ek80_reference_manual_a4_english.pdf?OpenElement)

Note that the program ER60 runs the EK60 echosounders, but for the new generation the program and the sounder are synonymous and both called EK80.

### Some literature

For those that want to get a head we recommend the following reading material:

  * Simmonds & MacLennan's Fisheries Acoustics [@simmonds2005]
  * The ICES calibration CRR [@demer2015]
  * Rolf _et al._'s recent paper on categorization with LSSS [@korneliussen2017]

On Monday 16th mention was made of the `scrutiny workshop` held by
participants in the IESNS (May) survey in Reykjavík in March 2015. The
report of the workshop was added as an appendix to an ICES report of
the WKSCRUT workshop held in the autumn the same year:

  * [Report of the ICES scrutiny worshop](http://ices.dk/sites/pub/Publication%20Reports/Expert%20Group%20Report/SSGIEOM/2015/WKSCRUT15.pdf) with the IESNS workshop report as an addendum [@ices2015] 

'Bergmálshandbók Hafró' or the MFRI acoustics manual has been given
[bookdown-treatment](https://github.com/sigurdurthorjonsson/bergmals_handbok)
and can now be found with a couple of new appendices
[online](http://www.hafro.is/~sigurdur/bergmals_handbok). The
LSSS-course/workshop will hopefully yield additions/improvements to the manual.
 
## Collection of material from previous courses and acoustic data on Hafró-net

Acoustic data and course materials from previous LSSS-courses, held both at Hafró and at IMR, Bergen, are available on file server Hafrún, accessible as `/u5/bergmal` in linux, Windows users can gain access by typing in `\\hafrun\u5\` in the address bar of Windows File Explorer and then descend into the folder `bergmal`. 

### LSSS-course materials

Course materials from a course held at IMR in Bergen in Febrary 2018
are are available (and also earlier LSSS-courses we've commisioned or attended), courtesy of Rolf Korneliussen and colleagues, are to be found under `bergmal` in folder:

`LSSS_namskeid/LSSS_Bergen_Feb_2018`

with 4 sub-directories containing pdf-s of help files and presentations:


- `1_LSSS_CURRENT_VERSION/DOCUMENTATION_LSSS_2_3_0_rc` with PDF-help accompanying LSSS and its modules,


- ` 2_ACOUSTICS` has materials on acoustics and application in fisheries research,

- `3_LSSS_BASIC` has extensive materials regarding basic use of LSSS suitable for selfstudy during easter :-), and finally:

- `4_LSSS_ADVANCED` has course materials from the advanced part of an LSSS-course

### Acoustic data

A significant proportion of the acoustic data collection of
Hafró is available under `bergmal` in the directory `EK60raw`, organized in
subfolders by survey (`[AB]YYYY_NR`, where [AB] is denotes wether the survey was conducted on Árni or Bjarni). Course/workshop participants can locate surveys of
interest, copy them to their personal drives and set up analysis
in LSSS.

We have established and aim to maintain a comprehensive but read-only version of `LSSS_DATA` from our surveys in this area of Hafró-net, existing data in that directory have yet to be quality assured and the process has to be formalized and disciplined somewhat (along with LSSS-database synchronization). See  (missing chapter in) 'gæðahandbók' for acoustic surveys.

 
# A draft workplan
___

## Part I


The course will be held in the meeting room on the first floor, there
is space for 10-15 people, on an 'early bird gets a seat' basis. Bring
your lap- or desktop. The preliminary plan is to meet at
__13:00-16:00__ on days the course is given / we meet for a
workshop. _Note that the themes and intitals are tentative, and we may
shuffle things around._

### WEEK 1

#### Wednesday, 2018-04-04

* Introduction to LSSS - sþj
* Basic use of LSSS - sþj 
* Scrutiny workshop - everyone
    
#### Thursday, 2018-04-05

* Scrutiny workshop continued - everyone
* Comparison of results - everyone

Some notes from the first two sessions are available [here](week1.html).

### WEEK 2

#### Monday, 2018-04-16

* Categorization of blue whiting - ahó, gjó, sþj, ... 

#### Thursday, 2018-04-17

* Bottom as a reference - bb, sþj

Some notes from sessions three and four are available [here](week2.html).

### WEEK 3

#### Monday, 2018-04-23

* Multifrequency categorization with LSSS - pr

#### Tuesday, 2018-04-24

* Multifrequency categorization with LSSS contd. - pr

#### Thursday, 2018-04-26

* Open for suggestions - everyone

#### Friday, 2018-04-27

* 13:00 - "Happy hour"
    * Any other LSSS-buissness
    * Next steps in LSSS

## Part II or to be continued


Prior to multi-vessel surveys we will aim for 1/2- or 1-day crash courses for the personnel manning the acoustic instruments.

We'll probably get instructors from IMR/Marec for a full LSSS-course in the not too distant future. 

Here are some aspects of LSSS and acoustic data collection and house-keeping that need to be considered:

* Utilization of sonar in fisheries research

* Broad-band capable echosounders, big data

* Standardizing Hafró/MFRI processing of acoustics data.

* Central DB of survey results, read-only.

* [Testing out Deep Vision acoustic integration with LSSS](https://www.deepvision.no/deep-vision-acoustic-integration)

* ...

## Addendums

* Bits and pieces - collection of stuff made in the follow-up to the course and workshop.

# Citations
___


